name: Check Code & Govuln

on:
  workflow_dispatch:

jobs:
  check-code:
    name: Staticcheck
    runs-on: ubuntu-latest
    container:
      image: golang:1.21.5
    if: github.ref_type != 'tag'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run staticcheck
        run: staticcheck ./...

  govulncheck:
    name: Go Vulnerability Check
    runs-on: ubuntu-latest
    container:
      image: golang:1.24.2
    if: github.ref_type != 'tag'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run govulncheck
        run: govulncheck ./...
